# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: b9f398529c4ce411f66331ff36af03cac93bd4558bc2f3482e21626f06926e5c49e4991b1bfba763483d286e3a325bef3dca49e2db66df92190713e438835601

test:
  secret_key_base: afa855b67058f8aafa84e3f49684aecbb9ac8139231c7df7307a5d3d63014d82cb1fb2db876eda749a65ce61a28f875ac7ab6766bd1dffd5a666b0921d58ed86

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
